# Generated by Django 5.0.1 on 2024-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kinokatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("adress", models.CharField(max_length=100, verbose_name="Адрес")),
                ("phone", models.IntegerField()),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Кинокаталоги",
                "verbose_name_plural": "Кинокаталог",
            },
        ),
    ]
